### ISSUE TITLE
skyblock play causes exception

### ISSUE THREAD

**Issue by Nunction** [Seadragon91/SkyBlock#2]
Whenever I execute "/skyblock play" the following appears in the log:
~~~
Player <Name> is executing command "/skyblock play" in world "skyblock" at world age 985. 
Write: Requesting datatypes not present in the cBlockArea. Got only 0x03, requested 0x23
Parameters on the stack Warn 
LUA: Write: Requesting datatypes not present in the cBlockArea. Got only 0x03, requested 0x23
Stack trace:
[C](-1): Write
Plugins/SkyBlock/code/CreateIsland.lua(43): CreateIsland
Plugins/SkyBlock/code/commands/cmd_SkyBlock.lua(46): (no name)
Stack trace end
Error in <attached> calling function <callback>()
~~~
I added the "World=skyblock" and "Plugin=SkyBlock" to settings.ini. I am able to join the world, which puts me into an empty world without any platform. 
Additional installed plugins:  
    IRChat (version 4)
    WorldEdit (version 13)
    Core (version 15)
    SkyBlock (version 3)
    ChatLog (version 3)

**Comment by Seadragon91** [comment]
Thanks for reporting should be now fixed in master.

**Comment by Nunction** [comment]
Great thanks.
